-build:
  image: quay.io/ukhomeofficedigital/ckan:v1.1.0
  script:
    - cp ckan/configuration/ckan.ini $CKAN_CONFIG/ckan.ini
    - cp ckan/init/ $USER_SCRIPT_DIR
publish:
  docker:
    registry: quay.io
    username: $$QUAY_USERNAME
    password: $$QUAY_PASSWORD
    email: chris.davidson@digital.homeoffice.gov.uk
    repo: ukhomeofficedigital/data-catalogue
    tag: $$TAG
    file: Dockerfile
    when:
      branch: master
