build:
  image: quay.io/ukhomeofficedigital/ckan:v1.1.0
  commands:
    - cp ckan/configuration/ckan.ini $CKAN_CONFIG/ckan.ini
    - cp ckan/init/* $USER_SCRIPT_DIR
    - mkdir $CKAN_PLUGINS
    - cp -r ckan/plugins/* $CKAN_PLUGINS
    - yum install -y wget && yum clean all
    - wget -O /tmp/release-1.0.0.tar.gz https://github.com/open-data/ckanext-scheming/archive/release-1.0.0.tar.gz
    - tar -C $CKAN_PLUGINS -xvf /tmp/release-1.0.0.tar.gz 
    - mv $CKAN_PLUGINS/ckanext-scheming-release-1.0.0/ $CKAN_PLUGINS/ckanext-scheming/
    - rm /tmp/release-1.0.0.tar.gz
publish:
  docker:
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    registry: quay.io
    username: $$QUAY_USER
    password: $$QUAY_PASSWORD
    email: $$QUAY_EMAIL
    repo: quay.io/ukhomeofficedigital/data-catalogue
    storage_driver: overlay
    tag:
      - latest
      - v0.4."$DRONE_BUILD_NUMBER"
    when:
      branch: drone
