-build:
  image: quay.io/ukhomeofficedigital/ckan:v1.1.0
  commands:
    - echo "Hello World"
    - env
    - cp ckan/configuration/ckan.ini $CKAN_CONFIG/ckan.ini
    - cp ckan/init/ $USER_SCRIPT_DIR
    - cp ckan/plugins $CKAN_PLUGINS
    - ls ckan/plugins
    - echo "Goodbye World"
