sudo: required
dist: trusty

service:
  - docker

script:
  - docker build -t homeofficeckan .
  - sudo docker run -d --privileged=true --name=solr milafrerichs/ckan_solr
  - sudo docker run -d --privileged=true --name=db ckan/postgresql
  - sudo docker run -d --privileged=true --name=ckan -p 80:80 --link db:db --link solr:solr homeofficeckan
  - sleep 30
  - curl -o /tmp/homeofficeckan.output.html localhost
  - ls /
  - cd /app/ckan/plugins/ckanext-datacatalogue_theme
  - nosetests --ckan --with-pylons=test.ini ckanext/iauthfunctions/tests

after_failure:
  - docker logs homeofficeckan
