---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: data-catalogue
  name: data-catalogue
spec:
  ports:
    -
      name: http
      nodePort: 30314
      port: 80
      targetPort: http
  selector:
    name: data-catalogue
  type: NodePort
