---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: db
  name: db
spec:
  replicas: 1
  selector:
    name: db
    version: v0
  template:
    metadata:
      labels:
        name: db
        version: v0
    spec:
      containers:
        -
          image: ckan/postgresql
          imagePullPolicy: Always
          livenessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "PGPASSWORD=ckan psql -U ckan ckan -c \"SELECT version()\""
            initialDelaySeconds: 60
            timeoutSeconds: 1
          name: db
          ports:
            -
              containerPort: 5432
              name: postgresql
          readinessProbe:
            exec:
              command:
                - bash
                - "-c"
                - "PGPASSWORD=ckan psql -U ckan ckan -c \"SELECT version()\""
            initialDelaySeconds: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
      restartPolicy: Always
